# src/config/settings.yaml
spark:
  app_name: "RelatorioPedidosRecusadosLegitimos"

paths:
  pagamentos: "./data/input/dataset-json-pagamentos/data/pagamentos"
  pedidos: "./data/input/datasets-csv-pedidos/data/pedidos/"
  output: "./data/output/pedidos_recusados_legitimos_2025.parquet"

file_options:
  pedidos_csv:
    compression: "gzip"
    header: True
    sep: ";"